CREATE SEQUENCE SEQ_USERS
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;

CREATE TABLE TBL_USERS (
    USER_ID INTEGER DEFAULT SEQ_USERS.NEXTVAL NOT NULL,
    NAME VARCHAR2(100) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    PASSWORD VARCHAR(100) NOT NULL
);